### ISSUE TITLE
Livrer les captures d'écran des vues Entreprises et entreprise

### ISSUE THREAD

**Issue by NicolasGlassey** [NicolasGlassey/TPICarfleet_Backend#6]
Impossible de me connecter à l'application. J'ai ouvert un ticket chez le client pour les obtenirs.

En attendant inspirez-vous des vidéos livrées. Je reviens vers vous dès que j'obtiens la réponses.

**Comment by yannickcpnv** [comment]
Je peux faire le développement en me basant sur les vidéos. Les captures d'écrans ne seront nécessaires que pour le rapport de projet.

**Comment by NicolasGlassey** [comment]
Bonjour Yannick,

Voici les captures demandées.

Bonne suite de TPI
[Carfleet1_Entreprise.pdf](https://github.com/NicolasGlassey/TPICarfleet_Backend/files/6477273/Carfleet1_Entreprise.pdf)
