### ISSUE TITLE
Sprint n°2 non ouvert

### ISSUE THREAD

**Issue by yannickcpnv** [NicolasGlassey/TPICarfleet_Backend#8]
Bonjour M. @NicolasGlassey,

Le sprint n°2 n'est pas ouvert dans IceScrum, pouvez vous l'ouvrir svp.

Lorsqu'il est en "TODO", je ne peux pas mêttre à jour les tâches.

**Comment by NicolasGlassey** [comment]
C est corrigé. Bon long we.
